---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent
  labels:
    app: parent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parent
  template:
    metadata:
      labels:
        app: parent
    spec:
      containers:
        - name: parent
          image: "httpd:alpine"
          imagePullPolicy: Always
