apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parent
  labels:
    app: parent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: parent
    spec:
      containers:
        - name: parent
          image: "httpd:alpine"
          imagePullPolicy: Always
