---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subchart
  labels:
    app: subchart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subchart
  template:
    metadata:
      labels:
        app: subchart
    spec:
      containers:
      - name: subchart
        image: "nginx:alpine"
        imagePullPolicy: Always
