apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subchart
  labels:
    app: subchart
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subchart
    spec:
      containers:
        - name: subchart
          image: "nginx:alpine"
          imagePullPolicy: Always
